version: '3.8'
services:
  sequence-service:
    image: soyummy/sequence:latest
    container_name: sequenceTest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/your_database  # MariaDB의 서비스 이름을 사용하여 연결
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: soyummy/mariadb:latest
    container_name: sequenceDB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

    ports:
      - "3307:3306"