version: '3'
services:
  sequence-service:
    image: soyummy/sequence:sequenceSpring
    container_name: sequenceTest
    command: "java -jar ./sequenceTest-0.0.1-SNAPSHOT.jar"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/your_database  # MariaDB의 서비스 이름을 사용하여 연결
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: soyummy/mariadb:11.4 # 만약 에러나면 mariadb:11.4로만 한 번 실행해보세요 그리고 나서 docker 내에서 tag 명령어를 사용해서 이름을 이렇게 바꿔주고 다시 실행시키면 됩니다.
    container_name: sequenceDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
    ports:
      - "3307:3306"
    volumes:
      - sequenceTest:/var/lib/mysql

volumes:
  sequenceTest:
